import type { CareCase } from "./types";

export const DEMO_CASES: CareCase[] = [
  {
    id: "elena",
    name: "Elena Rossi",
    age: 74,
    relationship: "Mother",
    caregiver: "Sofia Rossi, daughter",
    setting: "Home, day 11 after HF discharge",
    conditionLine: "HFpEF, AF on anticoagulation, mild dementia, polypharmacy",
    summary:
      "Elena was discharged 11 days ago after acute decompensated heart failure with preserved ejection fraction. She lives with her daughter Sofia. New evening confusion, 4 lb weight gain in 3 days, extra pillows at night. Sofia started OTC ibuprofen for Elena's knee so she could sleep.",
    status: "unstable",
    isDemo: true,
    defaultQuery:
      "She gained 4 pounds, needs extra pillows, and I started ibuprofen for her knee. She is more confused after dinner. What should I watch and what do I ask the clinic tomorrow?",
    medications: [
      { name: "Lisinopril", dose: "10 mg", schedule: "morning", notes: "held one day in hospital for creatinine bump" },
      { name: "Metoprolol succinate", dose: "50 mg", schedule: "morning", started: "this admission" },
      { name: "Furosemide", dose: "40 mg", schedule: "morning", notes: "Sofia is unsure whether to give a second dose if ankles swell" },
      { name: "Spironolactone", dose: "25 mg", schedule: "morning" },
      { name: "Apixaban", dose: "5 mg", schedule: "twice daily", notes: "for atrial fibrillation" },
      { name: "Donepezil", dose: "10 mg", schedule: "night" },
      { name: "Sertraline", dose: "50 mg", schedule: "morning", started: "6 weeks ago" },
      { name: "Omeprazole", dose: "20 mg", schedule: "morning", notes: "started in hospital" },
      { name: "Ibuprofen (OTC)", dose: "400 mg", schedule: "evening PRN knee", started: "3 days ago", notes: "not on discharge list" },
      { name: "Acetaminophen", dose: "500 mg", schedule: "PRN", notes: "also in a PM cold tablet last weekend" },
    ],
    documents: [
      {
        id: "elena-dc",
        title: "Discharge summary (excerpt)",
        kind: "discharge",
        date: "11 days ago",
        body: "Admit: acute decompensated HFpEF, AF with RVR that responded to metoprolol. Echo: EF 58%, mild LVH. Cr 1.3 on discharge (1.1 baseline). Weight 162 lb on discharge. Instructions: 2 g sodium, daily weights, call for +3 lb in a day. Follow-up HF clinic 14 days. Anticoagulation continued. No NSAIDs mentioned in counseling notes.",
      },
      {
        id: "elena-note",
        title: "Sofia's kitchen-table log",
        kind: "note",
        date: "today",
        body: "Mon 164, Tue 165, Wed 166, today 166. Ankles indent. Sleeps in recliner since Tuesday. Ate half a sandwich. Knew my name this morning, asked what year it was after dinner. No chest pain. Urine seemed darker. Neighbor brought leftover lasagna (salty).",
      },
    ],
    graph: {
      nodes: [
        { id: "elena", label: "Elena, 74", kind: "person" },
        { id: "sofia", label: "Sofia (caregiver)", kind: "person" },
        { id: "hf", label: "HFpEF", kind: "condition" },
        { id: "af", label: "Atrial fibrillation", kind: "condition" },
        { id: "dem", label: "Mild dementia", kind: "condition" },
        { id: "conf", label: "Evening confusion", kind: "symptom" },
        { id: "wt", label: "+4 lb / 3 d", kind: "symptom" },
        { id: "orth", label: "Recliner sleep", kind: "symptom" },
        { id: "nsaid", label: "Ibuprofen OTC", kind: "medication" },
        { id: "apix", label: "Apixaban", kind: "medication" },
        { id: "loop", label: "Furosemide", kind: "medication" },
        { id: "ace", label: "Lisinopril", kind: "medication" },
        { id: "home", label: "Home day 11", kind: "place" },
      ],
      edges: [
        { from: "sofia", to: "elena", label: "cares for" },
        { from: "elena", to: "hf", label: "lives with" },
        { from: "elena", to: "af", label: "lives with" },
        { from: "elena", to: "dem", label: "lives with" },
        { from: "hf", to: "wt", label: "signal" },
        { from: "hf", to: "orth", label: "signal" },
        { from: "nsaid", to: "hf", label: "may worsen" },
        { from: "nsaid", to: "apix", label: "bleed stack" },
        { from: "ace", to: "nsaid", label: "kidney stack" },
        { from: "loop", to: "nsaid", label: "kidney stack" },
        { from: "conf", to: "elena", label: "new" },
        { from: "elena", to: "home", label: "setting" },
      ],
    },
  },
  {
    id: "jamal",
    name: "Jamal Okonkwo",
    age: 8,
    relationship: "Son",
    caregiver: "Amara Okonkwo, mother",
    setting: "Home + school, post-ER",
    conditionLine: "Severe persistent asthma, no written action plan",
    summary:
      "Jamal has had two emergency-department visits this season for asthma. Amara is using the albuterol inhaler 8–10 times some days. There is a cat. The school nurse does not have a current authorization. Controller inhaler technique has never been checked with a spacer at clinic.",
    status: "watch",
    isDemo: true,
    defaultQuery:
      "He used albuterol almost hourly after gym yesterday. There is still no paper plan and school cannot give the inhaler. What do I put in front of the pediatrician on Thursday?",
    medications: [
      { name: "Albuterol MDI", dose: "2 puffs", schedule: "rescue, currently 8–10× some days", notes: "no spacer at school" },
      { name: "Fluticasone MDI", dose: "110 mcg 2 puffs", schedule: "twice daily", notes: "Amara is unsure he tastes it; sometimes skipped when well" },
      { name: "Cetirizine", dose: "5 mg", schedule: "night", notes: "for allergies" },
    ],
    documents: [
      {
        id: "jamal-er",
        title: "ER after-visit summary",
        kind: "discharge",
        date: "16 days ago",
        body: "Wheeze, O2 93% on arrival, responded to nebulizers and steroids. Discharge: continue controller, albuterol q4h PRN, follow up PCP 3–5 days. 'Asthma action plan discussed' is checked; no copy is in the parent packet Amara kept. Peak flow not used.",
      },
      {
        id: "jamal-note",
        title: "Amara's night log",
        kind: "note",
        date: "this week",
        body: "Cough after soccer. Sits forward on the bed. Used rescue at 22:00, 01:30, 05:10 Tuesday. Cat sleeps on his feet. Grandmother smokes on the balcony; door is often open. School sent him to office twice; they called me to pick up because they cannot give the inhaler.",
      },
    ],
    graph: {
      nodes: [
        { id: "jamal", label: "Jamal, 8", kind: "person" },
        { id: "amara", label: "Amara (mother)", kind: "person" },
        { id: "asthma", label: "Severe asthma", kind: "condition" },
        { id: "alb", label: "Albuterol overuse", kind: "medication" },
        { id: "ics", label: "Fluticasone", kind: "medication" },
        { id: "cat", label: "Cat in bedroom", kind: "place" },
        { id: "school", label: "School — no auth", kind: "place" },
        { id: "night", label: "Night cough", kind: "symptom" },
        { id: "plan", label: "Missing action plan", kind: "task" },
      ],
      edges: [
        { from: "amara", to: "jamal", label: "cares for" },
        { from: "jamal", to: "asthma", label: "lives with" },
        { from: "alb", to: "asthma", label: "rescue only" },
        { from: "ics", to: "asthma", label: "controller" },
        { from: "cat", to: "asthma", label: "trigger" },
        { from: "night", to: "jamal", label: "signal" },
        { from: "school", to: "plan", label: "blocked" },
        { from: "plan", to: "jamal", label: "needed" },
      ],
    },
  },
  {
    id: "priya",
    name: "Priya Mehta",
    age: 52,
    relationship: "Spouse",
    caregiver: "Raj Mehta, husband",
    setting: "Awaiting staging, community hospital",
    conditionLine: "New invasive ductal carcinoma, staging pending",
    summary:
      "Core biopsy last week: invasive ductal carcinoma, ER/PR and HER2 pending. Surgical oncology visit in four days. Raj has been reading survival blogs and buying turmeric capsules. Two teenagers at home. Priya is not sleeping. No nurse navigator assigned yet.",
    status: "new",
    isDemo: true,
    defaultQuery:
      "The biopsy says invasive ductal carcinoma. Staging scans are next week. What is actually happening, what should we not do, and what do we ask the surgeon so we do not waste the visit?",
    medications: [
      { name: "Atorvastatin", dose: "20 mg", schedule: "night" },
      { name: "Turmeric / curcumin capsules", dose: "unknown", schedule: "twice daily", started: "this week", notes: "Raj ordered online" },
      { name: "Melatonin", dose: "5 mg", schedule: "night", started: "this week" },
    ],
    documents: [
      {
        id: "priya-path",
        title: "Pathology (patient portal excerpt)",
        kind: "labs",
        date: "6 days ago",
        body: "Left breast, 10 o'clock, ultrasound-guided core biopsy. Invasive ductal carcinoma, Nottingham grade 2. Ductal carcinoma in situ present. Lymphovascular invasion: not identified on this sample. ER/PR/HER2: pending. Clinical correlation and staging recommended.",
      },
      {
        id: "priya-note",
        title: "Raj's questions (unfiltered)",
        kind: "note",
        date: "today",
        body: "Does waiting for scans let it spread? Alkaline water? Should we fly to a big center this week? Do I tell the kids it is 'a lump' or cancer? She wants lumpectomy only. A forum said everyone needs chemo first. I bought curcumin because a thread said it 'starves tumors'.",
      },
    ],
    graph: {
      nodes: [
        { id: "priya", label: "Priya, 52", kind: "person" },
        { id: "raj", label: "Raj (husband)", kind: "person" },
        { id: "kids", label: "Two teens", kind: "person" },
        { id: "idc", label: "IDC, grade 2", kind: "condition" },
        { id: "stage", label: "Staging pending", kind: "task" },
        { id: "visit", label: "Surg-onc, 4 days", kind: "task" },
        { id: "forum", label: "Forum noise", kind: "place" },
        { id: "curc", label: "Curcumin OTC", kind: "medication" },
        { id: "sleep", label: "Insomnia", kind: "symptom" },
      ],
      edges: [
        { from: "raj", to: "priya", label: "cares for" },
        { from: "kids", to: "priya", label: "need a story" },
        { from: "priya", to: "idc", label: "new" },
        { from: "idc", to: "stage", label: "waiting on" },
        { from: "stage", to: "visit", label: "before menu" },
        { from: "forum", to: "raj", label: "floods" },
        { from: "curc", to: "visit", label: "disclose" },
        { from: "sleep", to: "priya", label: "now" },
      ],
    },
  },
];

export function cloneDemoCases(): CareCase[] {
  return JSON.parse(JSON.stringify(DEMO_CASES)) as CareCase[];
}
