import type { CorpusChunk } from "./types";

export const CORPUS: CorpusChunk[] = [
  {
    id: "hf-weight",
    title: "Daily weight as an early heart-failure signal",
    topic: "Heart failure",
    tags: ["heart failure", "weight", "edema", "caregiver", "orthopnea"],
    source: "American Heart Association — Heart Failure Tools",
    sourceUrl: "https://www.heart.org/en/health-topics/heart-failure",
    body: "Families are often asked to weigh the person at the same time each morning, after urinating, before breakfast, in similar clothes. A gain of about 2–3 pounds in a day or 5 pounds in a week is a commonly taught prompt to call the care team, because it can mean extra fluid rather than extra food. Pair the number with symptoms: new swelling of legs or abdomen, needing more pillows to sleep, waking short of breath, or a dry cough. Do not change diuretic doses from a chart at home. Bring the weight log to the visit.",
  },
  {
    id: "hf-orthopnea",
    title: "Orthopnea and paroxysmal nocturnal dyspnea",
    topic: "Heart failure",
    tags: ["orthopnea", "shortness of breath", "night", "heart failure"],
    source: "NHLBI — Heart Failure",
    sourceUrl: "https://www.nhlbi.nih.gov/health/heart-failure",
    body: "Orthopnea is shortness of breath that appears when lying flat and eases sitting up. Paroxysmal nocturnal dyspnea is a sudden night-time episode of breathlessness. Both are educational warning patterns in people already living with heart failure. They are reasons to contact the clinician the same day, not to self-adjust medicines. Note how many pillows are used and whether the person sleeps in a chair.",
  },
  {
    id: "nsaid-hf",
    title: "NSAIDs and heart failure or kidney risk",
    topic: "Medication safety",
    tags: ["ibuprofen", "naproxen", "nsaid", "heart failure", "kidney", "otc"],
    source: "FDA NSAID medication guides; AHA heart-failure self-care",
    sourceUrl: "https://www.fda.gov/drugs/postmarket-drug-safety-information-patients-and-providers/nsaid-nonsteroidal-anti-inflammatory-drugs-information",
    body: "Over-the-counter pain medicines in the NSAID class (ibuprofen, naproxen, and many cold combinations) can cause the body to hold salt and water, raise blood pressure, and stress the kidneys. In a person with heart failure this can undo diuretic work. NSAIDs also increase bleeding risk when combined with anticoagulants. Acetaminophen is often discussed as an alternative for simple pain, but dosing limits and liver disease still matter. A caregiver should not start or stop these products without checking the medication list with a pharmacist or clinician — especially after a recent hospitalization.",
  },
  {
    id: "nsaid-bleed",
    title: "NSAIDs plus anticoagulants: bleeding watch",
    topic: "Medication safety",
    tags: ["apixaban", "warfarin", "bleeding", "nsaid", "eliquis"],
    source: "FDA anticoagulant patient information",
    sourceUrl: "https://www.fda.gov/consumers/consumer-updates/think-youve-got-your-blood-thinner-under-control-think-again",
    body: "Anticoagulants such as apixaban, rivaroxaban, warfarin, and dabigatran reduce clot risk and raise bleeding risk. Adding an NSAID (ibuprofen, naproxen) or high-dose aspirin stacks that risk. Watch-for signs families are taught: unusual bruising, black stools, pink or red urine, coughing or vomiting blood, a severe headache unlike usual, or a fall with head strike. Do not interpret a bruise as proof of a dose problem. Contact the prescribing clinician or emergency services depending on severity.",
  },
  {
    id: "acei-nsaid-diuretic",
    title: "The triple whammy: ACE inhibitor, diuretic, NSAID",
    topic: "Medication safety",
    tags: ["lisinopril", "enalapril", "furosemide", "nsaid", "kidney", "triple"],
    source: "UK MHRA and nephrology patient-safety briefings on 'triple whammy'",
    sourceUrl: "https://www.gov.uk/drug-safety-update/nsaids-and-renal-function",
    body: "Combining an ACE inhibitor or ARB, a diuretic, and an NSAID is a well-described pattern for acute kidney injury, especially in older adults, during illness with poor intake, or in hot weather. Educational action is to flag the combination to a clinician or pharmacist, watch urine output and swelling, and avoid starting OTC NSAIDs 'just for the knee' after discharge. Laboratory checks (creatinine, potassium) are a clinician decision.",
  },
  {
    id: "polypharmacy-elder",
    title: "Polypharmacy in older adults",
    topic: "Geriatrics",
    tags: ["polypharmacy", "beers", "elderly", "confusion", "falls"],
    source: "American Geriatrics Society Beers Criteria (educational overview); NIA",
    sourceUrl: "https://www.nia.nih.gov/health/medicines-and-medication-management",
    body: "Taking five or more standing medicines is common after a hospital stay and is called polypharmacy. Risk is not the count alone — it is duplicate classes, drugs that increase fall or confusion risk, and medicines started in hospital that were meant to be temporary. New confusion after a medication change is a prompt to bring the actual bottles (or a photo of every label) to the clinician. Do not discontinue a heart, blood-thinner, or dementia medicine because an article listed it as 'potentially inappropriate'. Deprescribing is a supervised process.",
  },
  {
    id: "delirium",
    title: "Delirium is a medical event, not 'just aging'",
    topic: "Geriatrics",
    tags: ["confusion", "delirium", "elderly", "uti", "medication"],
    source: "NIH National Institute on Aging — Delirium",
    sourceUrl: "https://www.nia.nih.gov/health/hospitalization-and-surgery/delirium-older-adults",
    body: "Delirium is a sudden change in attention, awareness, or thinking. It fluctuates, often worse at night. Common associated factors: infection (including urinary), new medicines, withdrawal, dehydration, low oxygen, unmanaged pain, and hospital environments. Unlike typical dementia progression, delirium starts over hours to days. Family is often the first to notice. This is a same-day call, not a wait-for-the-next-visit pattern. Families should bring a baseline description: what was the person like last week?",
  },
  {
    id: "donepezil",
    title: "Cholinesterase inhibitors: what families are told to watch",
    topic: "Dementia",
    tags: ["donepezil", "aricept", "dementia", "nausea", "bradycardia"],
    source: "NIA Alzheimer’s disease medications overview",
    sourceUrl: "https://www.nia.nih.gov/health/alzheimers-treatment/how-alzheimers-disease-treated",
    body: "Donepezil and related medicines are used in Alzheimer disease and some other dementias. They do not reverse the disease. Educational side-effect watches include nausea, diarrhea, vivid dreams, appetite change, and, less often, slow heart rate or fainting. They interact with other drugs that slow the heart. Stopping suddenly can worsen thinking for a time. Any change belongs with the prescriber, not a forum taper schedule.",
  },
  {
    id: "spironolactone-k",
    title: "Potassium-sparing diuretics and salt substitutes",
    topic: "Medication safety",
    tags: ["spironolactone", "potassium", "salt substitute", "ace inhibitor"],
    source: "MedlinePlus — Spironolactone",
    sourceUrl: "https://medlineplus.gov/druginfo/meds/a682627.html",
    body: "Spironolactone helps the body lose water while holding potassium. Combined with ACE inhibitors, ARBs, potassium supplements, or potassium-based salt substitutes, potassium can rise to dangerous levels. Symptoms of high potassium can be vague: weakness, nausea, palpitations. Families should mention salt-substitute use at visits. Do not start a 'heart-healthy' salt substitute from a grocery aisle without checking the label with a pharmacist.",
  },
  {
    id: "furosemide",
    title: "Loop diuretics: practical caregiver notes",
    topic: "Heart failure",
    tags: ["furosemide", "lasix", "diuretic", "dizziness", "kidney"],
    source: "MedlinePlus — Furosemide",
    sourceUrl: "https://medlineplus.gov/druginfo/meds/a682858.html",
    body: "Furosemide increases urine output and is a mainstay in fluid overload. Caregivers often notice dizziness on standing, cramps, and more bathroom trips. Missing doses plus extra salt can bring fluid back quickly. Taking an extra tablet 'because the legs look puffy' is a common harmful improvisation. Track weight, swelling, and dizziness, and ask the clinic what their call threshold is. Illness with vomiting or poor drinking is a reason to call before the next scheduled dose change.",
  },
  {
    id: "beta-blocker-hf",
    title: "Beta blockers after a heart-failure admission",
    topic: "Heart failure",
    tags: ["metoprolol", "carvedilol", "beta blocker", "fatigue", "pulse"],
    source: "AHA — Heart failure medicines",
    sourceUrl: "https://www.heart.org/en/health-topics/heart-failure/treatment-options-for-heart-failure/medications-used-to-treat-heart-failure",
    body: "Metoprolol, carvedilol, and bisoprolol are often continued or started around a heart-failure stay. Fatigue, slow pulse, and cold hands are commonly discussed. Suddenly stopping can be harmful. A resting pulse that is much lower than the person's usual, new fainting, or wheezing in someone with lung disease are 'call today' items. Families should record pulse if they have been taught how, not guess from a fitness watch during a walk.",
  },
  {
    id: "ssri-elder",
    title: "SSRIs in older adults: sodium and fall watch",
    topic: "Geriatrics",
    tags: ["sertraline", "ssri", "hyponatremia", "falls", "sodium"],
    source: "NIA and FDA antidepressant guides for older adults",
    sourceUrl: "https://www.nia.nih.gov/health/mental-and-emotional-health/depression-and-older-adults",
    body: "Sertraline and related antidepressants can, especially in the first weeks or after a dose change, be associated with low sodium in older adults — presenting as confusion, unsteadiness, or headache. They also have small additive fall and bleeding signals with other drugs. Abrupt stop can cause withdrawal feelings. New confusion after a psychiatric-med change is a laboratory and medication-review question for the clinician, not proof the dementia has 'suddenly progressed'.",
  },
  {
    id: "omeprazole",
    title: "Proton-pump inhibitors after hospital",
    topic: "Medication safety",
    tags: ["omeprazole", "ppi", "hospital", "deprescribing"],
    source: "FDA PPI safety communications (educational)",
    sourceUrl: "https://www.fda.gov/drugs/drug-safety-and-availability/fda-drug-safety-communication-possible-increased-risk-fractures-hip-wrist-and-spine-use-proton-pump",
    body: "Omeprazole and other PPIs are often started in hospital for ulcer protection. Many people stay on them for years without a review. Long-term use has been associated in studies with nutrient issues, infection risk, and fracture signals — association is not a reason to stop today. The useful caregiver move is to ask: 'Is this still needed, and for how long?' at the post-discharge visit.",
  },
  {
    id: "fall-prevention",
    title: "Fall prevention at home after discharge",
    topic: "Geriatrics",
    tags: ["falls", "home", "night", "dizziness", "hip"],
    source: "CDC STEADI / older-adult fall prevention",
    sourceUrl: "https://www.cdc.gov/falls/about/index.html",
    body: "Falls are a leading reason older adults return to hospital. Practical environmental checks: night lights to the bathroom, removing loose rugs, shoes with backs, glasses on before standing, sitting at the bedside for a minute after waking (postural change). New dizziness on standing can be medicines, dehydration, or blood pressure. A head strike while on an anticoagulant is an emergency-level event even if the person 'seems fine'.",
  },
  {
    id: "stroke-fast",
    title: "Stroke warning signs (F.A.S.T. / BE-FAST)",
    topic: "Emergency",
    tags: ["stroke", "fast", "face", "speech", "emergency"],
    source: "American Stroke Association — F.A.S.T.",
    sourceUrl: "https://www.stroke.org/en/about-stroke/stroke-symptoms",
    body: "Face drooping, Arm weakness, Speech difficulty, Time to call emergency services. BE-FAST also includes Balance sudden trouble and Eyes sudden vision loss. These signs can be from stroke or from low blood sugar in some people with diabetes — still call emergency services rather than waiting to see if it 'passes'. Note the time symptoms started. Do not give aspirin unless a clinician has already instructed that specific person for that event.",
  },
  {
    id: "er-when",
    title: "When caregivers are taught to use emergency services",
    topic: "Emergency",
    tags: ["emergency", "911", "chest pain", "breathing", "bleeding"],
    source: "AHA and CDC emergency warning-sign pages",
    sourceUrl: "https://www.heart.org/en/health-topics/heart-attack/warning-signs-of-a-heart-attack",
    body: "Educational emergency patterns: chest pain or pressure lasting more than a few minutes; severe trouble breathing; sudden weakness or speech change; fainting; seizure; uncontrolled bleeding; blue lips; a first severe 'worst headache'; overdose. For suicidal thoughts, contact emergency services or 988 in the US. A care briefing tool is not a substitute for those numbers. If you are unsure whether it is an emergency, treat it as one.",
  },
  {
    id: "visit-prep",
    title: "How to run a 15-minute clinic visit",
    topic: "Caregiving",
    tags: ["visit", "questions", "advocate", "medication list"],
    source: "AHRQ Question Builder / Ask Me 3",
    sourceUrl: "https://www.ahrq.gov/questions/question-builder/index.html",
    body: "Most post-discharge visits are short. Families who leave with answers usually bring: (1) a one-page timeline of the last week, (2) every bottle or a photo of labels, (3) three ranked questions, (4) vital signs or weights if they were asked to track them, (5) a second person to listen. Ask Me 3: What is the main problem? What do we need to do? Why is it important? Ask for the teach-back: 'Can you watch me explain the plan so I do not miss a step?'",
  },
  {
    id: "med-rec",
    title: "Medication reconciliation after hospital",
    topic: "Medication safety",
    tags: ["reconciliation", "discharge", "pharmacy", "duplicate"],
    source: "AHRQ patient safety — medication reconciliation",
    sourceUrl: "https://www.ahrq.gov/patient-safety/settings/hospital/match/index.html",
    body: "Discharge lists, the pharmacy fill, and the bottles on the counter often disagree. Duplicate blood pressure pills, a home NSAID next to a new anticoagulant, and 'take as before' for a medicine that was stopped in hospital are classic errors. Reconcile within 48 hours with a pharmacist if possible. Mark anything the family does not recognize. Never crush a pill to 'make it easier' unless a pharmacist says that specific tablet may be crushed.",
  },
  {
    id: "caregiver-burnout",
    title: "Caregiver strain is a clinical risk factor",
    topic: "Caregiving",
    tags: ["burnout", "sleep", "respite", "depression", "family"],
    source: "AARP / National Alliance for Caregiving; NIA caregiver health",
    sourceUrl: "https://www.nia.nih.gov/health/caregiving/getting-help-caregiving",
    body: "Unpaid family caregivers provide most long-term care. Strain shows up as missed medications, irritability, sleep loss, skipped meals, and delayed calls for help. It is associated with worse outcomes for both people. Practical supports: a second trained person for night meds, adult day programs, a pharmacy blister pack, a written night-time routine, and the caregiver's own primary-care visit. Naming strain in the visit is not selfish; it is part of the care plan.",
  },
  {
    id: "asthma-action",
    title: "Written asthma action plans",
    topic: "Asthma",
    tags: ["asthma", "action plan", "green yellow red", "child", "school"],
    source: "NHLBI Asthma Action Plan",
    sourceUrl: "https://www.nhlbi.nih.gov/resources/asthma-action-plan",
    body: "A written asthma action plan uses green (everyday controller and prevention), yellow (getting worse — add or increase as the clinician wrote), and red (medical help now) zones, often tied to symptoms and sometimes peak flow. Without a written plan, families tend to overuse albuterol and underuse inhaled corticosteroids. Schools need a copy and authorization to give medicine. This is a document to request at the next visit, not to invent from a website.",
  },
  {
    id: "albuterol-overuse",
    title: "Rescue inhaler overuse is a control signal",
    topic: "Asthma",
    tags: ["albuterol", "rescue", "inhaler", "controller", "ics"],
    source: "NHLBI / CDC asthma management",
    sourceUrl: "https://www.cdc.gov/asthma/inhaler_video/default.htm",
    body: "Albuterol relieves tight airways quickly but does not treat the inflammation that drives most persistent asthma. Needing rescue more than twice a week (outside of exercise, per many education materials), emptying canisters monthly, or using it through the night are signals that control is poor. The educational response is to review technique, controller adherence, triggers, and the action plan with the clinician — not to add a second rescue inhaler from a relative.",
  },
  {
    id: "ics-adherence",
    title: "Inhaled corticosteroids only work when they are taken",
    topic: "Asthma",
    tags: ["ics", "fluticasone", "budesonide", "controller", "thrush"],
    source: "CDC asthma and NHLBI EPR educational summaries",
    sourceUrl: "https://www.cdc.gov/asthma/faqs.htm",
    body: "Inhaled corticosteroids reduce airway swelling. They do not give a 'hit' the way albuterol does, so families stop them when the child 'seems fine'. That is when exacerbations return. Rinse and spit after a steroid inhaler to lower thrush risk; use a spacer if prescribed. Growth concerns should be discussed with the prescriber rather than used as a reason to skip doses. Technique matters as much as the prescription.",
  },
  {
    id: "spacer-technique",
    title: "Spacers and inhaler technique",
    topic: "Asthma",
    tags: ["spacer", "technique", "child", "mdi", "school"],
    source: "CDC inhaler and spacer videos",
    sourceUrl: "https://www.cdc.gov/asthma/inhaler_video/default.htm",
    body: "Metered-dose inhalers used without a spacer often deposit medicine on the tongue. For children, a valved holding chamber with or without a mask is commonly taught. One puff at a time, slow breaths, wait between puffs as instructed. Schools should have a labeled spacer that stays there. If the child coughs or tastes the medicine strongly every time, technique — not 'the asthma is mild' — is the first question.",
  },
  {
    id: "asthma-triggers",
    title: "Common asthma triggers at home and school",
    topic: "Asthma",
    tags: ["cat", "smoke", "virus", "cold air", "allergens"],
    source: "CDC — Common asthma triggers",
    sourceUrl: "https://www.cdc.gov/asthma/triggers.html",
    body: "Viral infections are the most common trigger of childhood exacerbations. Others: smoke (including visitors), furred pets, dust mites, cockroaches, mold, cold air, exercise, strong odors, and some NSAIDs in sensitive people. Removing a beloved cat is a family decision with the clinician, not an internet ultimatum; mitigation (bedroom off-limits, HEPA, washing) is often the first experiment. Never use an unvented gas heater in a child's sleep space.",
  },
  {
    id: "asthma-red",
    title: "Asthma red zone — educational emergency pattern",
    topic: "Asthma",
    tags: ["red zone", "emergency", "lips blue", "ribs", "speak"],
    source: "NHLBI asthma action plan red zone",
    sourceUrl: "https://www.nhlbi.nih.gov/resources/asthma-action-plan",
    body: "Red-zone patterns families are taught: the rescue inhaler is not helping, the child cannot speak full sentences, ribs or neck muscles pull in, lips or nails look blue or gray, peak flow (if used) is in the red range written on their plan, or the child is collapsing into sleep from work of breathing. This is emergency-care time. Do not drive across town to 'the usual pediatrician' if breathing is that hard — use emergency services.",
  },
  {
    id: "school-asthma",
    title: "School medication authorization",
    topic: "Asthma",
    tags: ["school", "nurse", "504", "authorization", "child"],
    source: "CDC asthma-friendly schools",
    sourceUrl: "https://www.cdc.gov/asthma/schools.html",
    body: "A child can have a perfect home plan and still be unprotected at school if the nurse lacks a current authorization, a labeled inhaler, and a spacer. Many districts also need an emergency action plan and parent contacts. Ask for a 504 or individualized health plan if asthma is interrupting class. The next clinic visit should produce paperwork, not only a refill.",
  },
  {
    id: "cancer-first",
    title: "The first weeks after a cancer diagnosis",
    topic: "Cancer",
    tags: ["breast cancer", "diagnosis", "staging", "second opinion", "shock"],
    source: "American Cancer Society — After diagnosis",
    sourceUrl: "https://www.cancer.org/cancer/diagnosis-staging/after-diagnosis.html",
    body: "Staging (how far cancer has spread) usually happens after the biopsy confirms cancer and before a final treatment menu. Waiting for scans is not the same as 'doing nothing' — it is how teams avoid the wrong surgery. Shock, insomnia, and frantic forum reading are normal. Useful moves: one notebook, one friend as recorder at visits, a request to copy the pathology report, and asking whether a nurse navigator exists. Online survival statistics are often outdated or the wrong subtype.",
  },
  {
    id: "breast-pathology",
    title: "What a breast pathology report is trying to say",
    topic: "Cancer",
    tags: ["pathology", "receptor", "her2", "grade", "invasive ductal"],
    source: "American Cancer Society — Understanding your pathology report",
    sourceUrl: "https://www.cancer.org/cancer/types/breast-cancer/understanding-a-breast-cancer-diagnosis.html",
    body: "Invasive ductal carcinoma means cancer cells have moved into surrounding breast tissue. Grade describes how abnormal cells look. Receptor tests (estrogen, progesterone, HER2) steer medicine choices later; they are not a DIY prognosis. Margins, lymphovascular invasion, and nodes wait for surgery or staging studies. Families should ask the oncologist to walk the report line by line. A forum that treats all 'IDC' as one disease is misleading.",
  },
  {
    id: "cancer-questions",
    title: "Questions for a first surgical-oncology visit",
    topic: "Cancer",
    tags: ["questions", "surgery", "lumpectomy", "mastectomy", "navigator"],
    source: "ACS and NCI talking-with-your-doctor guides",
    sourceUrl: "https://www.cancer.gov/about-cancer/coping/adjusting-to-cancer/talk-with-doctor",
    body: "High-yield questions: What subtype and stage do we have so far? What information is still missing? Is breast-conserving surgery an option, and what would reconstruction or radiation mean? Do we need genetics counseling? Who is the coordinator between surgery, medical oncology, and radiation? How soon must we decide, really? What symptoms after biopsy or port placement should we call about? Bring a list; shock will erase it.",
  },
  {
    id: "cancer-misinfo",
    title: "Cancer misinformation after diagnosis",
    topic: "Cancer",
    tags: ["forums", "alkaline", "detox", "misinformation", "supplements"],
    source: "NCI / ACS misinformation guidance",
    sourceUrl: "https://www.cancer.gov/about-cancer/causes-prevention/risk",
    body: "Alkaline diets, 'detox' IVs, and unregulated supplements are aggressively marketed to newly diagnosed families. Some herbs interact with anesthesia and later with chemotherapy. The educational rule: show every supplement bottle at the oncology visit, and treat viral posts as unverified until the team says otherwise. Hope is not the same as a protocol. Second opinions at a cancer center are a standard option, not a betrayal of the first surgeon.",
  },
  {
    id: "kids-cancer-talk",
    title: "Talking with teenagers about a parent's cancer",
    topic: "Cancer",
    tags: ["children", "teen", "communication", "family", "school"],
    source: "ACS — Helping children when a family member has cancer",
    sourceUrl: "https://www.cancer.org/cancer/caregivers/helping-children.html",
    body: "Teenagers detect secrecy and fill gaps with worse stories. Developmentally they want honesty with a plan: what we know, what we do not, who they can ask, how school and activities will be handled, and that the cancer is not their fault and not contagious. Let them choose how much detail. Name a spare adult they can text. Watch for sleep change, dropping grades, or risk-taking as signals to bring in school counseling — not as proof they 'don't care'.",
  },
  {
    id: "988",
    title: "988 Suicide & Crisis Lifeline",
    topic: "Emergency",
    tags: ["988", "suicide", "crisis", "mental health"],
    source: "988 Suicide & Crisis Lifeline (SAMHSA)",
    sourceUrl: "https://988lifeline.org",
    body: "In the United States, 988 is a 24/7 confidential line, text, and chat service for people in suicidal crisis or emotional distress, and for the people who care about them. If someone is in immediate danger, call emergency services. Caregiver despair after a diagnosis or a night of delirium is a reason to use these numbers, not a character test.",
  },
  {
    id: "acetaminophen",
    title: "Acetaminophen ceilings and hidden sources",
    topic: "Medication safety",
    tags: ["acetaminophen", "tylenol", "liver", "otc", "cold medicine"],
    source: "FDA acetaminophen safety",
    sourceUrl: "https://www.fda.gov/drugs/information-drug-class/acetaminophen-information",
    body: "Acetaminophen is in many pain and cold products. Stacking a 'PM' tablet, a sinus mix, and extra Tylenol is a classic liver-injury pattern. People with liver disease need individualized limits from their clinician. It does not treat inflammation the way NSAIDs do, which is why it is often preferred in heart failure — not because it is risk-free. Keep a running total for the day on a sticky note during illness.",
  },
  {
    id: "low-sodium-hf",
    title: "Sodium and fluid teaching in heart failure",
    topic: "Heart failure",
    tags: ["sodium", "diet", "fluid", "canned soup", "heart failure"],
    source: "AHA heart-failure lifestyle",
    sourceUrl: "https://www.heart.org/en/health-topics/heart-failure/treatment-options-for-heart-failure/lifestyle-changes-for-heart-failure",
    body: "Many programs teach a sodium limit (often discussed around 2,000 mg/day, individualized). The hidden load is canned soup, deli meat, sauces, and restaurant meals, not the salt shaker. Fluid limits are not universal — they are prescribed for some people. Families should ask for the actual numbers on the discharge sheet rather than copying a blog. A 'low sodium' label can still be high if the serving size is tiny.",
  },
  {
    id: "infection-elder",
    title: "Infection in older adults can look like confusion",
    topic: "Geriatrics",
    tags: ["uti", "pneumonia", "infection", "fever", "confusion"],
    source: "CDC older-adult infection and NIA delirium pages",
    sourceUrl: "https://www.cdc.gov/pneumonia/prevention/index.html",
    body: "Older adults often do not spike a high fever. A urinary or chest infection may present as a fall, anorexia, or sudden confusion. Caregivers should note urine smell/pain, cough, and oral intake, and call rather than starting leftover antibiotics. Not every confused elder has a UTI — unnecessary antibiotics harm — but new confusion is still a same-day clinical question.",
  },
  {
    id: "apixaban",
    title: "Direct oral anticoagulants: missed doses and procedures",
    topic: "Medication safety",
    tags: ["apixaban", "eliquis", "doac", "surgery", "missed dose"],
    source: "FDA / manufacturer patient guides for apixaban (educational)",
    sourceUrl: "https://www.fda.gov/consumers/consumer-updates/think-youve-got-your-blood-thinner-under-control-think-again",
    body: "Apixaban and similar medicines have shorter memory than warfarin — missing several doses raises clot risk; extra doses raise bleed risk. Dental work, colonoscopy, and falls with head strike all require a clinician plan, not a forum 'hold for 3 days' rule. Families should keep a wallet card that the person is anticoagulated. Do not add ibuprofen for arthritis on your own.",
  },
  {
    id: "teach-back",
    title: "Teach-back: the family safety habit",
    topic: "Caregiving",
    tags: ["teach-back", "literacy", "adherence", "discharge"],
    source: "AHRQ teach-back method",
    sourceUrl: "https://www.ahrq.gov/patient-safety/reports/engage/interventions/teachback.html",
    body: "Teach-back means the family explains the plan in their own words while the clinician listens for gaps. It is the most evidence-backed discharge habit that costs nothing. Use it for inhaler technique, weight-call thresholds, and which medicine is new. Shame about 'not getting it' is common; the method assumes the explanation failed, not the family.",
  },
  {
    id: "not-advice",
    title: "What an educational briefing is not",
    topic: "Safety",
    tags: ["disclaimer", "scope", "diagnosis", "advice"],
    source: "FDA / FTC consumer health-information principles",
    sourceUrl: "https://www.fda.gov/consumers/consumer-updates",
    body: "Educational materials can name patterns (for example, NSAIDs and heart failure) that clinicians already teach. They cannot know this person's ejection fraction, potassium, or goals of care. They cannot diagnose the cause of confusion or design a taper. Any tool that speaks in prescriptions, or that hides uncertainty, is outside its lane. The product of a briefing is better questions and a safer wait — or a faster emergency call.",
  },
  {
    id: "dementia-care-hours",
    title: "The scale of unpaid dementia and family care",
    topic: "Caregiving",
    tags: ["dementia", "unpaid", "training", "hours"],
    source: "Alzheimer’s Association Facts and Figures; NAC/AARP caregiver reports",
    sourceUrl: "https://www.alz.org/alzheimers-dementia/facts-figures",
    body: "Tens of millions of US adults provide unpaid care. A small minority report formal training in medical tasks they already perform: injections, wound care, medication management, delirium watch. The gap is not motivation — it is a system that discharges complexity onto the kitchen table. Tools that replace judgment with a diagnosis make that worse. Tools that structure observation, questions, and escalation can make the next 72 hours safer.",
  },
];

export const CORPUS_BY_ID = Object.fromEntries(CORPUS.map((c) => [c.id, c]));
